# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='edit_date',
            field=models.DateField(null=True),
        ),
    ]
