# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 12:46
from __future__ import unicode_literals

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20180119_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 13, 46, 37, 140079)),
        ),
    ]
