# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-23 18:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_auto_20180123_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 18, 48, 0, 239141)),
        ),
    ]
