# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-23 18:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_auto_20180123_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 18, 55, 12, 71251)),
        ),
    ]
