# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 18:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_auto_20180128_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(blank=True, null=True, upload_to='music/static/music/images/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 30, 18, 8, 0, 683887)),
        ),
    ]
