# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 17:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_auto_20180130_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(default='music/static/music/images/default.jpg', upload_to='music/static/music/images/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 17, 46, 53, 90238)),
        ),
    ]
