# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 11:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_auto_20180212_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 12, 12, 37, 53, 938823)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='music/static/music/images/avatars/default.png', null=True, upload_to='music/static/music/images/avatars/'),
        ),
    ]
