# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 11:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_auto_20180212_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(blank=True, default='/music/static/music/images/default.jpg', null=True, upload_to='music/static/music/images/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 12, 12, 39, 20, 239760)),
        ),
    ]
