# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 10:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0027_auto_20180212_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 11, 34, 57, 593643)),
        ),
    ]
